import { FormEvent, useEffect, useRef, useState } from "react";
import * as api from "./api";
import type { CreatorConfig, CreatorDraft, CreatorSnapshot } from "./types";
import { beijingInput, fromBeijingInput, beijingDisplay } from "./creatorTime";
import ScreenshotCreator from "./ScreenshotCreator";
import { dailyPreparation, beijingDay } from "./creatorPlan";
import themes from "./creatorThemes.json";
import { selectedThemes, publishPreview, wordingHints } from "./creatorWriting";
import CreatorReferencePanel from "./CreatorReferencePanel";

const kinds=["实用分享","开发记录","热点整理","轻松日常"];
const labels={review:"待审核",ready:"待发布",published:"已发布",skipped:"已跳过"};
const usd=(n:number)=>`$${(n/1e6).toFixed(6)}`;
export default function CreatorWorkbench({onSettings}:{onSettings:()=>void}) {
  const [s,setS]=useState<CreatorSnapshot>(); const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  const [hot,setHot]=useState(false);const [filter,setFilter]=useState("pending");const [query,setQuery]=useState(""); const [limit,setLimit]=useState(50);
  const [confirm,setConfirm]=useState<"approve"|"plan"|"end"|"retry"|null>(null);
  const [includeSources,setIncludeSources]=useState(true);const [article,setArticle]=useState<Awaited<ReturnType<typeof api.workbenchSnapshot>>["article"]>();
  const formRef=useRef<HTMLFormElement>(null);const [goalInput,setGoalInput]=useState<string|null>(null);const [personaTopics,setPersonaTopics]=useState("");
  const [topicNames,setTopicNames]=useState(["创业","搞笑","开发"]);const topicInitialized=useRef(false);
  const [referenceHandles,setReferenceHandles]=useState<string[]>([]);
  const [referenceBusy,setReferenceBusy]=useState(false);
  const [restart,setRestart]=useState<{config:CreatorConfig;expectedIds:number[]}|null>(null);
  const refresh=async()=>{setS(await api.creatorSnapshot());};
  useEffect(()=>{void refresh().catch(e=>setNotice(String(e)));const timer=window.setInterval(()=>void refresh().catch(e=>setNotice(String(e))),2000);void api.workbenchSnapshot().then(s=>{setArticle(s.article);setPersonaTopics(s.persona.topics);}).catch(e=>setNotice(String(e)));return()=>window.clearInterval(timer);},[]);
  useEffect(()=>setGoalInput(null),[s?.todayGoal]);
  useEffect(()=>{if(s&&!topicInitialized.current){topicInitialized.current=true;if(s.run?.config.topics?.length&&!s.run.config.rewriteTarget)setTopicNames(s.run.config.topics.filter(t=>themes.some(x=>x.name===t)));}},[s]);
  const act=async(work:()=>Promise<unknown>,text:string)=>{setBusy(true);try{await work();await refresh();setNotice(text);}catch(e){setNotice(String(e));}finally{setBusy(false);}};
  const buildConfig=(discard=false):CreatorConfig=>{
    const d=new FormData(formRef.current!);const f=(k:string)=>String(d.get(k)??"");
    const target=Number(f("goal"));const plan=dailyPreparation(target,s?.todayPublished??0,discard?0:s?.drafts.filter(x=>["review","ready"].includes(x.status)).length??0);
    if(!plan.valid||!plan.count)throw new Error("请填写1–200的目标，且大于今天已发布数；已有足够草稿时可以选择放弃旧稿重新生成。");
    const topics=selectedThemes(d.getAll("topics").map(String),f("customTopics"));
    return {topic:f("topic").trim()||"按选定话题，结合我的人设与领域创作",topics,materials:f("materials"),count:plan.count,dailyTarget:target,hot,keywords:f("keywords").split(/[,，\n]/).map(x=>x.trim()).filter(Boolean),kinds:d.getAll("kinds").map(String),minLikes:Number(f("minLikes")),xCapUsd:hot?f("xCap"):(s?.preferences.defaultXCapUsd??"0.01"),aiCapUsd:f("aiCap"),referenceHandles};
  };
  const start=async(e:FormEvent<HTMLFormElement>)=>{
    e.preventDefault();let config:CreatorConfig;try{config=buildConfig();}catch(e){setNotice(String(e));return;}
    setFilter("pending");setQuery("");setLimit(50);setNotice(`正在启动：准备${config.count}篇内容并自动排期…`);
    await act(()=>api.startCreatorRun(config),"目标已保存，正在按多个话题轮换准备内容。你只需点击一次；分段保存后即可先复制发布，结束后自动排期。");
  };
  const exportCalendar=()=>act(async()=>{const blob=new Blob([await api.creatorCalendar()],{type:"text/calendar;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="XUnFollow-北京时间发布提醒.ics";a.click();window.setTimeout(()=>URL.revokeObjectURL(url),10000);},"已导出审核通过的排期，导入系统日历可在应用退出后提醒。勿重复导入造成重复通知。");
  if(!s) return <section className="settings-page">正在读取创作工作台…{notice}</section>;
  const r=s.run;const locked=busy||s.running||referenceBusy;const unfinished=Boolean(r&&r.phase!=="done");
  const pending=s.drafts.filter(d=>["review","ready"].includes(d.status));const goal=Number(goalInput??s.todayGoal);const preparation=dailyPreparation(goal,s.todayPublished,pending.length);
  const todayPlanned=pending.filter(d=>d.scheduledAt&&beijingDay(d.scheduledAt)===beijingDay()).length;
  const goalChanged=goal!==s.todayGoal;
  const list=s.drafts.filter(d=>(filter==="all"||filter==="pending"&&["review","ready"].includes(d.status)||d.status===filter)&&`${d.title} ${d.body}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <section className="creator-desk">
    <div className="desk-heading"><div><p className="eyebrow">创作工作台 · 人工发布</p><h2>准备内容，按自己的节奏发布</h2><p className="wb-note">北京时间排期。不会打开、操作或自动发布到 X。生成、复制、提醒都不计入已发布。</p></div><button onClick={onSettings}>人设 / 模型 / 提醒设置</button></div>
    <div className="creator-summary"><div><strong>{s.todayPublished} / {s.todayGoal}</strong><span>今天已标记发布</span></div><div><strong>{todayPlanned}</strong><span>今日已排期 · 未发布</span></div><div><strong>{pending.length}</strong><span>可用草稿 · 不用重新生成</span></div><div><strong>{s.totalPublished}</strong><span>累计发布</span></div></div>
    <progress className="creator-progress" value={Math.min(s.todayPublished,s.todayGoal)} max={s.todayGoal} aria-label="今日发布进度" />
    <CreatorReferencePanel selected={referenceHandles} onSelection={setReferenceHandles} disabled={busy||s.running||unfinished} onReadingChange={setReferenceBusy}/>
    <section className="creator-form creator-daily-plan"><h3>1. 定目标，一次准备好内容</h3><form ref={formRef} onSubmit={e=>void start(e)}>
      <div className="creator-plan-controls"><label>今天计划发布几条？<input key={s.todayGoal} name="goal" type="number" min={1} max={200} defaultValue={s.todayGoal} required onInput={e=>setGoalInput(e.currentTarget.value)} /></label><button className="open-x" disabled={locked||unfinished||!preparation.valid||!preparation.count} type="submit">{s.running?"正在生成并排期…":unfinished?"请先继续或结束上一轮":preparation.count?`生成${preparation.count}篇${pending.length||s.todayPublished?"补齐目标":"内容"}并排期`:"已有足够草稿，直接复制发布"}</button><button className="creator-replan" type="button" disabled={locked||!preparation.valid} onClick={()=>setConfirm("plan")}>{goalChanged?"保存新目标并重新排期":"重新排期"}（不生成）</button></div>
      <div className="creator-restart-row"><button type="button" className="creator-restart" disabled={locked||unfinished||!pending.length||!preparation.valid||goal<=s.todayPublished} onClick={()=>{if(!formRef.current?.reportValidity())return;try{setRestart({config:buildConfig(true),expectedIds:pending.map(d=>d.id)});}catch(e){setNotice(String(e));}}}>放弃全部未发布草稿，重新生成</button><span className="wb-note">不是改写旧稿：按下面的主题、素材和选中的参考博主重新写。旧稿进入「已跳过」，可恢复。</span></div>
      <p className="wb-note">目标{preparation.valid?goal:"—"}条 − 今天已发布{s.todayPublished}条 − 可用草稿{pending.length}篇 = 还需准备{preparation.missing}篇。{preparation.missing>50&&"每次最多50篇，完成后再点一次补齐。"}改变数字不会自动扣费，点击生成才请求 API。完成后会按新目标重排未发布草稿；已发布不变。</p>
      <div className="creator-themes" role="group" aria-label="创作主题多选"><strong>创作主题 · 多选，整批轮换着写</strong><div className="creator-theme-chips">{themes.map(t=><label className={`check-label ${topicNames.includes(t.name)?"selected":""}`} key={t.name} title={t.hint}><input type="checkbox" name="topics" value={t.name} checked={topicNames.includes(t.name)} onChange={e=>setTopicNames(xs=>e.target.checked?[...xs,t.name]:xs.filter(x=>x!==t.name))}/>{t.name}</label>)}</div><p className="wb-note">不把所有主题写进同一条。短句、长短搭配，说完就停；擦边仅成年人、非露骨的暧昧玩笑。{s.preferences.creatorVoiceSamples.trim()?"已启用你的真实语气参考。":"想更像你？到设置贴3–5条自己写过的帖子。"}</p></div>
      <div className="wb-grid"><label>其他主题（逗号分隔，可留空）<input name="customTopics" maxLength={300} defaultValue={r?.config.topics?.filter(t=>!themes.some(x=>x.name===t)).join("，")} placeholder="例如：职场、生活吐槽、读书" /></label><label>补充领域 / 要求（选填）<input name="topic" maxLength={300} defaultValue={r&&!r.config.screenshot&&!r.config.rewriteTarget?r.config.topic:personaTopics} placeholder="例如：围绕小工具，少提AI，不要鸡汤" /></label>
      <label className="check-label wb-wide"><input type="checkbox" checked={hot} onChange={e=>setHot(e.target.checked)} />通过 API 找中文热点作为素材</label>
      {hot&&<><label>热点关键词（逗号分隔）<input name="keywords" required placeholder="AI, 独立开发" maxLength={400} /></label><label>最低点赞数<input name="minLikes" type="number" min={0} max={100000} defaultValue={5} /></label></>}
      <label>AI 费用上限（美元）<input name="aiCap" required defaultValue={s.preferences.defaultAiCapUsd} inputMode="decimal" /></label><label>搜索费用上限（美元）<input name="xCap" required defaultValue={s.preferences.defaultXCapUsd} inputMode="decimal" disabled={!hot} /></label></div>
      <details className="creator-options creator-inspiration"><summary>选题灵感 · 展开挑素材，不需要额外 API</summary><p className="wb-note">这些是创作角度，不是已经发生的事。选一个会放进补充要求；每批也会自动换角度，不照抄灵感句子。</p><div className="creator-inspiration-grid">{themes.filter(t=>topicNames.includes(t.name)).map(t=><div key={t.name}><strong>{t.name}</strong><p>{t.hint}</p>{t.seeds.map(seed=><button type="button" key={seed} disabled={locked} onClick={()=>{const field=formRef.current?.elements.namedItem("topic") as HTMLInputElement|null;if(field){field.value=[field.value,`灵感：${seed}`].filter(Boolean).join("；").slice(0,300);setNotice("灵感已放进补充要求。它是选题，不代表你的真实经历。");}}}>{seed} ＋</button>)}</div>)}</div>{!topicNames.length&&<p className="wb-note">先选一个内置主题，就能看到对应灵感；自定义话题也可以直接生成。</p>}</details>
      <details className="creator-options"><summary>补充真实素材 / 内容类型</summary><div className="wb-grid"><label className="wb-wide">真实素材 / 要包含的内容<textarea name="materials" rows={3} maxLength={12000} placeholder="自己的实践、产品变化、要点。开发记录必须填写；不替你虚构经历。" /></label>
      <div className="kind-options wb-wide">{kinds.map(k=><label className="check-label" key={k}><input name="kinds" value={k} type="checkbox" defaultChecked={k==="轻松日常"} />{k}</label>)}</div>
      </div></details><p className="wb-note">当前模型：{s.preferences.model}。一次点选可准备50篇，内部每5篇分段保存，无需逐批点击。生成会将主题、真实素材、语气样稿及本批已生成内容的开头结尾发送到官方 DeepSeek，避免句式重复。按北京时间{ s.preferences.creatorDayStart }–{s.preferences.creatorDayEnd}均匀排期，至少间隔5分钟；当天时段不够的会明确显示顺延日期。热点搜索最多6页，不足不会硬凑；费用上限不足会暂停并保留已生成内容。</p>
      {confirm==="plan"&&<div className="creator-confirm" role="alert"><p>保存今日目标{goal}条，并按北京时间{s.preferences.creatorDayStart}–{s.preferences.creatorDayEnd}重新安排{pending.length}篇未发布草稿（含手动时间）。不生成、不扣 API 费用，已发布内容不变。</p><button type="button" disabled={locked} onClick={()=>void act(async()=>{const target=Number(new FormData(formRef.current!).get("goal"));await api.saveCreatorGoal(target);await api.planCreator(true);setConfirm(null);setFilter("pending");setQuery("");},"目标已保存，未发布草稿已重新排期，没有请求 API。")}>确认重新排期</button><button type="button" onClick={()=>setConfirm(null)}>取消</button></div>}
    </form></section>
    {restart&&<section className="creator-confirm creator-restart-confirm" role="alert"><h3>确认放弃旧稿并重新生成？</h3><p>将当前全部{restart.expectedIds.length}篇未发布草稿移到「已跳过」，不会删除。今天已发布的{s.todayPublished}条和累计进度不变。按目标{restart.config.dailyTarget}条，先生成{restart.config.count}篇全新内容并排期；每轮最多50篇。</p><p>主题：{restart.config.topics?.join("、")||restart.config.topic} · 写法参考：{restart.config.referenceHandles?.map(n=>`@${n}`).join("、")||"不参考博主"}。本轮 AI 上限 ${restart.config.aiCapUsd}{restart.config.hot?`，热点搜索上限 $${restart.config.xCapUsd}`:"，不重新搜索热点"}。参考样本和人设会发往官方 DeepSeek，沿用缓存不再次收取博主读取费用。此操作会重新计费；失败时旧稿仍可从「已跳过」恢复。</p><div className="creator-actions"><button disabled={locked} className="open-x" onClick={()=>void act(async()=>{await api.restartCreatorRun(restart.config,restart.expectedIds);setRestart(null);setFilter("pending");setQuery("");setLimit(50);},"旧草稿已保留在「已跳过」，正在生成新内容；已发布进度不变。")}>确认放弃旧稿，按上限重新生成</button><button disabled={busy} onClick={()=>setRestart(null)}>取消，不修改旧稿</button></div></section>}
    <ScreenshotCreator preferences={s.preferences} disabled={locked||unfinished} act={act} />
    {r&&<section className="creator-run"><div className="task-head"><div><strong>{s.running?(r.phase==="searching"?"正在寻找素材…":"正在生成并保存…"):r.phase==="done"?"本轮已完成":"本轮已暂停"} · {r.generatedCount} / {r.config.count} 篇</strong><p className="wb-note">找到素材 {r.sourcesFound} 条 · 搜索 {usd(r.xSpentMicros)} / {usd(r.xCapMicros)} · AI {usd(r.aiSpentMicros)} / {usd(r.aiCapMicros)}</p></div><div className="creator-actions">{s.running?<button disabled={busy} onClick={()=>void act(api.stopCreatorRun,"已请求暂停，当前请求完成后停止，已有内容不会丢失。")}>暂停后续请求</button>:unfinished?<><button disabled={busy} onClick={()=>r.xUncertainMicros+r.aiUncertainMicros>0?setConfirm("retry"):void act(()=>api.resumeCreatorRun(false),"已从检查点继续，不重新生成已有草稿。")}>继续本轮</button><button disabled={busy} onClick={()=>setConfirm("end")}>结束本轮</button></>:null}</div></div><progress value={r.generatedCount} max={r.config.count} aria-label="生成进度" />
      {r.error&&<p className="creator-warning">{r.error}</p>}{r.xUncertainMicros+r.aiUncertainMicros>0&&<p className="creator-warning">可能计费：搜索 {usd(r.xUncertainMicros)}，AI {usd(r.aiUncertainMicros)}。已计入上限，不会自动重试。</p>}
      {!s.running&&unfinished&&<details><summary>手动提高本轮费用上限（不会自动继续）</summary><form className="inline-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void act(()=>api.raiseCreatorCap(String(d.get("kind")),String(d.get("cap"))),"上限已更新，请手动继续。");}}><select name="kind"><option value="ai">AI</option><option value="x">搜索</option></select><input name="cap" inputMode="decimal" placeholder="新的美元上限" required /><button disabled={busy}>更新</button></form></details>}
    </section>}
    <div className="desk-heading"><div><h3>2. 复制 → 自己发布 → 回来标记已发布</h3><p className="wb-note">按排期从前往后处理；发布标记立即更新顶部进度，内容会移到「已发布」，不会继续出现在待处理列表。</p></div><button disabled={busy} onClick={()=>void exportCalendar()}>导出提醒日历</button></div>
    <div className="creator-toolbar"><div className="wb-tabs">{[["pending","待处理"],["review","待审核"],["ready","待发布"],["published","已发布"],["skipped","已跳过"],["all","全部"]].map(([v,t])=><button className={filter===v?"active":""} key={v} onClick={()=>{setFilter(v);setLimit(50);}}>{t}</button>)}</div><input placeholder="搜索标题或内容" value={query} onChange={e=>{setQuery(e.target.value);setLimit(50);}} /></div>
    <div className="creator-actions"><label className="check-label"><input type="checkbox" checked={includeSources} onChange={e=>setIncludeSources(e.target.checked)} />复制时带来源链接</label><button disabled={locked||!r} onClick={()=>setConfirm("approve")}>本批检查完成，开启发布提醒</button></div>
    {confirm&&confirm!=="plan"&&<div className="creator-confirm" role="alert"><p>{confirm==="approve"?"请确认你已检查本批正文和来源。审核通过后进入待发布队列并启用提醒。":confirm==="end"?"结束本轮，不再请求 API；已经保存的草稿和费用记录会保留并排期。":"上次请求可能已被 Provider 计费，继续可能重复计费。不确定费用已保守计入上限，确认后才继续。"}</p><button disabled={busy} onClick={()=>void act(async()=>{if(confirm==="approve")await api.approveCreatorRun();else if(confirm==="end")await api.endCreatorRun();else await api.resumeCreatorRun(true);setConfirm(null);},"已完成操作")}>我已确认，继续</button><button onClick={()=>setConfirm(null)}>取消</button></div>}
    <p className="wb-note">提醒{s.preferences.remindersEnabled?"已开启":"未开启（到设置开启）"}。关闭窗口会隐藏到托盘；菜单“退出”会停止提醒。今天按北京时间统计；发布后请手动标记。共 {list.length} 篇，显示 {Math.min(limit,list.length)} 篇。</p>
    <div className="creator-cards">{list.slice(0,limit).map(d=><DraftCard key={d.id} d={d} busy={busy||(s.running&&r?.config.rewriteTarget===d.id)} rewriteAllowed={!locked&&!unfinished} includeSources={includeSources} act={act} />)}{!list.length&&<div className="empty-task">{filter==="pending"&&s.totalPublished?"当前没有待发布内容，已发布的内容在「已发布」里。到上方设定目标，一键准备今天需要的新内容。":"暂无内容，到上方设置目标并生成吧。"}</div>}</div>{list.length>limit&&<button onClick={()=>setLimit(n=>n+50)}>再显示50篇</button>}
    {article&&<details className="creator-form"><summary>保留的旧版文章：{article.topic}</summary><textarea readOnly value={article.body} rows={8}/></details>}
    {notice&&<div className="creator-notice" role="status">{notice}<button onClick={()=>setNotice("")}>关闭</button></div>}
  </section>;
}
function DraftCard({d,busy,rewriteAllowed,includeSources,act}:{d:CreatorDraft;busy:boolean;rewriteAllowed:boolean;includeSources:boolean;act:(f:()=>Promise<unknown>,text:string)=>Promise<void>}) {
  const [editing,setEditing]=useState(false);const [title,setTitle]=useState(d.title);const [body,setBody]=useState(d.body);const [time,setTime]=useState(beijingInput(d.scheduledAt));const [undo,setUndo]=useState(false);
  const [rewrite,setRewrite]=useState<"generate"|"restore"|null>(null);
  useEffect(()=>{if(!editing){setTitle(d.title);setBody(d.body);setTime(beijingInput(d.scheduledAt));}},[d.title,d.body,d.scheduledAt,editing]);
  const pending=d.status==="review"||d.status==="ready";
  const preview=publishPreview(d,includeSources);const hints=wordingHints(d.publishBody);
  return <article className={`creator-card ${d.status}`}><div className="task-head"><div><span className="creator-badge">{labels[d.status]} · {d.screenshot?"截图二次创作":d.topic||d.kind}</span><h3>{d.title}</h3><span className="wb-note">内部选题标题，不会复制到正文</span></div><span className="wb-note">北京 {beijingDisplay(d.scheduledAt)}{d.publishedAt&&` · 发布于 ${beijingDisplay(d.publishedAt)}`}</span></div>
    {editing?<><label>标题<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={160} /></label><label>正文<textarea rows={5} value={body} onChange={e=>setBody(e.target.value)} maxLength={5000}/></label><label>计划时间（北京时间）<input type="datetime-local" value={time} onChange={e=>setTime(e.target.value)} /></label><div className="creator-actions"><button disabled={busy} onClick={()=>void act(async()=>{await api.editCreatorDraft(d.id,title,body,time!==beijingInput(d.scheduledAt)?fromBeijingInput(time):undefined);setEditing(false);},"已保存修改，需要重新审核后才提醒。")}>保存修改</button><button onClick={()=>{setEditing(false);setBody(d.body);setTitle(d.title);setTime(beijingInput(d.scheduledAt));}}>取消</button></div></>:<div className="creator-paste-preview"><span className="wb-note">粘贴预览 · 正文{[...d.publishBody].length}字符 · 保留空行{includeSources&&d.sources.length?" · 附来源链接":""}</span><p className="creator-body">{preview}</p>{hints.map(h=><p className="creator-tone-hint" key={h}>措辞提醒：{h}（不是AI检测，是否修改由你决定）</p>)}</div>}
    <div className="creator-actions">{pending&&!editing&&<><button className="creator-copy" disabled={busy} onClick={()=>void act(()=>api.copyCreatorDraft(d.id,includeSources),"已按上面的粘贴预览复制，段间空行保留，不含内部标题。请自行发布，回来标记完成。")}>复制排版正文{includeSources&&d.sources.length?"与来源":""}</button><button disabled={busy} onClick={()=>setEditing(true)}>编辑 / 改时间</button>{d.status==="review"&&<button disabled={busy||!d.scheduledAt} onClick={()=>void act(()=>api.setCreatorStatus(d.id,"ready"),"审核通过，已加入发布提醒。")}>审核通过</button>}<button className="open-x" disabled={busy} onClick={()=>void act(()=>api.setCreatorStatus(d.id,"published"),"已标记发布，今日与累计进度已更新。")}>我已发布</button>{d.status==="ready"&&<button disabled={busy} onClick={()=>void act(()=>api.snoozeCreator(d.id),"15分钟后再提醒。")}>稍后15分钟</button>}<button disabled={busy} onClick={()=>void act(()=>api.setCreatorStatus(d.id,"skipped"),"已跳过，不再提醒。")}>跳过</button></>}
      {d.status==="published"&&(undo?<><span>确定撤销发布标记？</span><button disabled={busy} onClick={()=>void act(async()=>{await api.setCreatorStatus(d.id,"review");setUndo(false);},"已撤销标记，回到待审核。")}>确认撤销</button><button onClick={()=>setUndo(false)}>取消</button></>:<button onClick={()=>setUndo(true)}>撤销发布标记</button>)}{d.status==="skipped"&&<button disabled={busy} onClick={()=>void act(()=>api.setCreatorStatus(d.id,"review"),"恢复为待审核。")}>恢复草稿</button>}</div>
    {pending&&!editing&&<div className="creator-actions creator-rewrite-actions"><button disabled={!rewriteAllowed} onClick={()=>setRewrite("generate")}>改得更口语 · 调用 AI</button>{d.canUndoRewrite&&<button disabled={!rewriteAllowed} onClick={()=>setRewrite("restore")}>恢复改稿前版本 · 免费</button>}</div>}
    {rewrite&&pending&&<div className="creator-confirm">{rewrite==="generate"?<form onSubmit={e=>{e.preventDefault();const cap=String(new FormData(e.currentTarget).get("rewriteCap"));void act(async()=>{await api.rewriteCreatorDraft(d.id,cap);setRewrite(null);},"口语改稿已开始。成功后替换这条草稿并保留旧稿，来源、排期和发布进度不变；不会新增库存或操作 X。");}}><p>按最新人设、提示词和语气样稿改这条正文，不重新搜索热点。成功才替换，旧版可恢复；失败会保留原稿。会调用官方 DeepSeek 并计费，自然程度仍需你检查。</p><label>本次改稿 AI 费用上限（美元）<input name="rewriteCap" inputMode="decimal" defaultValue="0.02" required /></label><div className="creator-actions"><button type="submit" disabled={!rewriteAllowed}>确认上限，开始口语改稿</button><button type="button" onClick={()=>setRewrite(null)}>取消</button></div></form>:<><p>恢复上一次改稿前的正文和内部标题，会覆盖当前正文修改，需重新审核；发布时间、来源与发布进度不变。不调用 API、不扣费。</p><button disabled={!rewriteAllowed} onClick={()=>void act(async()=>{await api.undoCreatorRewrite(d.id);setRewrite(null);},"已恢复改稿前版本，发布进度不变。")}>确认恢复旧稿</button><button onClick={()=>setRewrite(null)}>取消</button></>}</div>}
    {(d.sources.length>0||d.imageIdea||d.screenshot)&&<details className="creator-sources"><summary>来源与配图建议 {d.screenshot?(d.sources.length?"· 截图二创 / 用户提供原帖链接":"· 截图二创 / 未提供原帖链接"):d.sources.length>0?`· ${d.sources.length} 条 API 来源`:"· 自主创作"}</summary>{d.sources.map(source=><div key={source.id}><strong>@{source.author}</strong><span className="wb-note">{d.screenshot?" · 用户填写，未抓取或核实原帖":` · ${beijingDisplay(source.createdAt)} · ${source.likes}赞`}</span><p>{source.text}</p><a href={source.url} onClick={e=>{e.preventDefault();void act(()=>api.openExternalProfile(source.url),"已按你的点击打开来源；应用不会操作页面。");}}>由你打开来源查看 ↗</a></div>)}{d.imageIdea&&<p>配图建议：{d.imageIdea}</p>}<p className="wb-note">来源内容可能不准确，请自行核实。原帖图片是否可用需你查看和确认授权；应用不下载图片，不代表获得使用权。</p></details>}
  </article>;
}
